package com.dormhelios.view;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalTenantsCard = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalTenantsLabel = new javax.swing.JLabel();
        tenantChangeLabel = new javax.swing.JLabel();
        tenantIconLabel = new javax.swing.JLabel();
        occupancyCard = new javax.swing.JPanel();
        occupancyTitleLabel = new javax.swing.JLabel();
        occupancyDetailLabel = new javax.swing.JLabel();
        occupancyIconLabel = new javax.swing.JLabel();
        occupancyRateLabel = new javax.swing.JLabel();
        revenueCard = new javax.swing.JPanel();
        revenueTitleLabel = new javax.swing.JLabel();
        monthlyRevenueLabel = new javax.swing.JLabel();
        revenueIconLabel = new javax.swing.JLabel();
        paymentStatusPanel = new javax.swing.JPanel();
        paymentStatusTitleLabel = new javax.swing.JLabel();
        chartPlaceholderPanel = new javax.swing.JPanel();
        recentActivitiesPanel = new javax.swing.JPanel();
        recentActivitiesTitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recentActivitiesList = new javax.swing.JList<>();
        remindersPanel = new javax.swing.JPanel();
        remindersTitleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        remindersList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        quickActionsTitleLabel = new javax.swing.JLabel();
        newPaymentButton = new javax.swing.JButton();
        addTenantButton = new javax.swing.JButton();
        sendReminderButton = new javax.swing.JButton();
        addRoomButton = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Total Tenants");

        totalTenantsLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalTenantsLabel.setText("6");

        tenantChangeLabel.setText("+5 this month");

        tenantIconLabel.setText("placeholder");

        javax.swing.GroupLayout totalTenantsCardLayout = new javax.swing.GroupLayout(totalTenantsCard);
        totalTenantsCard.setLayout(totalTenantsCardLayout);
        totalTenantsCardLayout.setHorizontalGroup(
            totalTenantsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalTenantsCardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(totalTenantsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totalTenantsCardLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(totalTenantsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tenantChangeLabel)
                            .addComponent(totalTenantsLabel))
                        .addContainerGap(305, Short.MAX_VALUE))
                    .addGroup(totalTenantsCardLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tenantIconLabel)
                        .addGap(5, 5, 5))))
        );
        totalTenantsCardLayout.setVerticalGroup(
            totalTenantsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalTenantsCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(totalTenantsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tenantIconLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalTenantsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenantChangeLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        occupancyTitleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        occupancyTitleLabel.setText("Occupancy Rate");

        occupancyDetailLabel.setText("15 out of 25 rooms");

        occupancyIconLabel.setText("placeholder");

        occupancyRateLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        occupancyRateLabel.setText("67%");

        javax.swing.GroupLayout occupancyCardLayout = new javax.swing.GroupLayout(occupancyCard);
        occupancyCard.setLayout(occupancyCardLayout);
        occupancyCardLayout.setHorizontalGroup(
            occupancyCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(occupancyCardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(occupancyCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(occupancyCardLayout.createSequentialGroup()
                        .addComponent(occupancyTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(occupancyIconLabel))
                    .addGroup(occupancyCardLayout.createSequentialGroup()
                        .addGroup(occupancyCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(occupancyRateLabel)
                            .addComponent(occupancyDetailLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        occupancyCardLayout.setVerticalGroup(
            occupancyCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(occupancyCardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(occupancyCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupancyTitleLabel)
                    .addComponent(occupancyIconLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(occupancyRateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(occupancyDetailLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        revenueTitleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        revenueTitleLabel.setText("Monthly Revenue");

        monthlyRevenueLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        monthlyRevenueLabel.setText("P5,000");

        revenueIconLabel.setText("placeholder");

        javax.swing.GroupLayout revenueCardLayout = new javax.swing.GroupLayout(revenueCard);
        revenueCard.setLayout(revenueCardLayout);
        revenueCardLayout.setHorizontalGroup(
            revenueCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenueCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(revenueCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthlyRevenueLabel)
                    .addGroup(revenueCardLayout.createSequentialGroup()
                        .addComponent(revenueTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(revenueIconLabel)))
                .addContainerGap())
        );
        revenueCardLayout.setVerticalGroup(
            revenueCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revenueCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(revenueCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revenueTitleLabel)
                    .addComponent(revenueIconLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monthlyRevenueLabel)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        paymentStatusTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentStatusTitleLabel.setText("Payment Status");

        chartPlaceholderPanel.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout chartPlaceholderPanelLayout = new javax.swing.GroupLayout(chartPlaceholderPanel);
        chartPlaceholderPanel.setLayout(chartPlaceholderPanelLayout);
        chartPlaceholderPanelLayout.setHorizontalGroup(
            chartPlaceholderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        chartPlaceholderPanelLayout.setVerticalGroup(
            chartPlaceholderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paymentStatusPanelLayout = new javax.swing.GroupLayout(paymentStatusPanel);
        paymentStatusPanel.setLayout(paymentStatusPanelLayout);
        paymentStatusPanelLayout.setHorizontalGroup(
            paymentStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentStatusPanelLayout.createSequentialGroup()
                .addGroup(paymentStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentStatusPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(paymentStatusTitleLabel))
                    .addGroup(paymentStatusPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(chartPlaceholderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        paymentStatusPanelLayout.setVerticalGroup(
            paymentStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentStatusPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(paymentStatusTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chartPlaceholderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        recentActivitiesTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        recentActivitiesTitleLabel.setText("Recent Activities");

        recentActivitiesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(recentActivitiesList);

        javax.swing.GroupLayout recentActivitiesPanelLayout = new javax.swing.GroupLayout(recentActivitiesPanel);
        recentActivitiesPanel.setLayout(recentActivitiesPanelLayout);
        recentActivitiesPanelLayout.setHorizontalGroup(
            recentActivitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentActivitiesPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(recentActivitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recentActivitiesTitleLabel))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        recentActivitiesPanelLayout.setVerticalGroup(
            recentActivitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentActivitiesPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(recentActivitiesTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        remindersTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        remindersTitleLabel.setText("Reminders & Alerts");

        remindersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(remindersList);

        javax.swing.GroupLayout remindersPanelLayout = new javax.swing.GroupLayout(remindersPanel);
        remindersPanel.setLayout(remindersPanelLayout);
        remindersPanelLayout.setHorizontalGroup(
            remindersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remindersPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(remindersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(remindersPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(remindersTitleLabel))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        remindersPanelLayout.setVerticalGroup(
            remindersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remindersPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(remindersTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        quickActionsTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        quickActionsTitleLabel.setText("Quick Actions");

        newPaymentButton.setText("New Payment");

        addTenantButton.setText("Add Tenant");

        sendReminderButton.setText("Send Reminder");

        addRoomButton.setText("Add Room");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(quickActionsTitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sendReminderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addTenantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(newPaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(quickActionsTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTenantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendReminderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalTenantsCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(occupancyCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paymentStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remindersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(revenueCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recentActivitiesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(revenueCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(occupancyCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalTenantsCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paymentStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recentActivitiesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(remindersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public void setTotalTenants(int count, String changeText) {
        totalTenantsLabel.setText(String.valueOf(count));
        tenantChangeLabel.setText(changeText); // e.g., "+5 this month"
    }

    public void setOccupancyRate(String rateText, String detailText) {
        occupancyRateLabel.setText(rateText); // e.g., "67%"
        occupancyDetailLabel.setText(detailText); // e.g., "10 out of 15 rooms"
    }

    public void setMonthlyRevenue(String revenueText) {
        monthlyRevenueLabel.setText(revenueText); // e.g., "P8,500.00" (Format in controller)
    }

    // Method to update the chart (Placeholder - requires a charting library)
    public JPanel getChartPanel() {
        return chartPlaceholderPanel;
        // The controller would get this panel and add the actual chart component
        // from a library like JFreeChart or Apache Commons Chart.
    }

    // Methods to update lists (Example using DefaultListModel for JList)
    public DefaultListModel<String> getRemindersListModel() {
        // Assuming a JList named remindersList is used
        if (!(remindersList.getModel() instanceof DefaultListModel)) {
            remindersList.setModel(new DefaultListModel<>());
        }
        return (DefaultListModel<String>) remindersList.getModel();
    }

    public DefaultListModel<String> getRecentActivitiesListModel() {
        // Assuming a JList named recentActivitiesList is used
        if (!(recentActivitiesList.getModel() instanceof DefaultListModel)) {
            recentActivitiesList.setModel(new DefaultListModel<>());
        }
        return (DefaultListModel<String>) recentActivitiesList.getModel();
    }
    
    public void addAddTenantButtonListener(ActionListener listener) {
        // Assuming button is named addTenantButton
        addTenantButton.addActionListener(listener);
    }

    public void addNewPaymentButtonListener(ActionListener listener) {
        // Assuming button is named newPaymentButton
        newPaymentButton.addActionListener(listener);
    }

    public void addSendReminderButtonListener(ActionListener listener) {
        // Assuming button is named sendReminderButton
        sendReminderButton.addActionListener(listener);
    }

    public void addAddRoomButtonListener(ActionListener listener) {
        // Assuming button is named addRoomButton
        addRoomButton.addActionListener(listener);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoomButton;
    private javax.swing.JButton addTenantButton;
    private javax.swing.JPanel chartPlaceholderPanel;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel monthlyRevenueLabel;
    private javax.swing.JButton newPaymentButton;
    private javax.swing.JPanel occupancyCard;
    private javax.swing.JLabel occupancyDetailLabel;
    private javax.swing.JLabel occupancyIconLabel;
    private javax.swing.JLabel occupancyRateLabel;
    private javax.swing.JLabel occupancyTitleLabel;
    private javax.swing.JPanel paymentStatusPanel;
    private javax.swing.JLabel paymentStatusTitleLabel;
    private javax.swing.JLabel quickActionsTitleLabel;
    private javax.swing.JList<String> recentActivitiesList;
    private javax.swing.JPanel recentActivitiesPanel;
    private javax.swing.JLabel recentActivitiesTitleLabel;
    private javax.swing.JList<String> remindersList;
    private javax.swing.JPanel remindersPanel;
    private javax.swing.JLabel remindersTitleLabel;
    private javax.swing.JPanel revenueCard;
    private javax.swing.JLabel revenueIconLabel;
    private javax.swing.JLabel revenueTitleLabel;
    private javax.swing.JButton sendReminderButton;
    private javax.swing.JLabel tenantChangeLabel;
    private javax.swing.JLabel tenantIconLabel;
    private javax.swing.JPanel totalTenantsCard;
    private javax.swing.JLabel totalTenantsLabel;
    // End of variables declaration//GEN-END:variables
}
